<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addproviderkeyid extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('provider', 'key_id', 'string', null,
            array(
                'type' => 'string',
                'fixed' => false,
                'unsigned' => false,
                'primary' => false,
                'unique' => true,
//                'notnull' => true,
                'autoincrement' => false,
                'length' => 16
            )
        );
    }

    public function down()
    {
        $this->removeColumn('provider', 'key_id');
    }
}